export const data = [
  { colour: '#f6f8f3', label: 'WHITE SATIN' },
  { colour: '#f3f5ec', label: 'WARM WHITE SATIN' },
  { colour: '#f6f8f6', label: 'APPLIANCE WHITE MAT+SAT' },
  { colour: '#ebf1f8', label: 'ARCTIC WHITE MAT+SAT' },
  { colour: '#f0e7d5', label: 'OFF WHITE MAT+SAT' },
  { colour: '#f1f0e6', label: 'RAL WHITE 9010 GLOSS' },
  { colour: '#eae1d5', label: 'WOODWIND MATT' },
  { colour: '#deceb1', label: 'MAGNOLIA MATT' },
  { colour: '#e8d7c7', label: 'RIVERGUM BEIGE MATT' },
  { colour: '#dfccb7', label: 'ALMOND MATT+SATIN' },
  { colour: '#e5e4e1', label: 'TUI TUFT MATT' },
  { colour: '#e3dfd6', label: 'CLOUD SATIN' },
  { colour: '#e3dfd4', label: 'TITANIA MATT+SATIN ' },
  { colour: '#dad4c9', label: 'CANVAS CLOTH MAT+SAT' },
  { colour: '#cdc6ba', label: 'O’KEEFE GREY MATT' },
  { colour: '#c5c1b3', label: 'BONE WHITE MATT' },
  { colour: '#b1b3af', label: 'APO GREY SATIN' },
  { colour: '#bec0bb', label: 'GULL GREY MATT+SATIN' },
  { colour: '#babab9', label: 'GHOST GREY MATT+SATIN' },
  { colour: '#c9b59c', label: 'DESERT SAND MATT' },
  { colour: '#b3a794', label: 'BRONCO MATT+SATIN' },
  { colour: '#a2957a', label: 'LICHEN MATT' },
  { colour: '#9f886d', label: 'KAURI MATT' },
  { colour: '#c43938', label: 'COLA RED SATIN' },
  { colour: '#924b3e', label: 'PIONEER RED MATT' },
  { colour: '#78493f', label: 'SCORIA MATT' },
  { colour: '#60839c', label: 'WEDGEWOOD MATT' },
  { colour: '#566970', label: 'WIZARD MATT' },
  { colour: '#4d575e', label: 'STORM BLUE MATT' },
  { colour: '#434a5d', label: 'NAVY MATT' },
  { colour: '#474e56', label: 'SLATE BLUE MATT' },
  { colour: '#575c60', label: 'NEW DENIM BLUE MAT+SAT' },
  { colour: '#3e5146', label: 'HAWTHORN GREEN SATIN' },
  { colour: '#4b5e4f', label: 'PERMANENT GREEN MAT+SAT' },
  { colour: '#888d74', label: 'MIST GREEN MAT+SAT' },
  { colour: '#757b69', label: 'BOND RIVERGUM MATT' },
  { colour: '#4b4b43', label: 'RANGOON GREEN MATT' },
  { colour: '#4e4c42', label: 'KARAKA MATT & SATIN' },
  { colour: '#60524a', label: 'LIGNITE MATT' },
  { colour: '#52483f', label: 'OLIVE MATT' },
  { colour: '#53443c', label: 'ANOTEC MID BRONZE MATT' },
  { colour: '#4b4545', label: 'ANOTEC DARK BRONZE MATT' },
  { colour: '#8f8d86', label: 'SANDSTONE GREY MAT+SAT' },
  { colour: '#81807a', label: 'MID GREY MATT' },
  { colour: '#505052', label: 'SLATE MATT' },
  { colour: '#494f52', label: 'DARK GREY MATT' },
  { colour: '#656157', label: 'THUNDER GREY MAT&SAT' },
  { colour: '#676768', label: 'FLINT MATT' },
  { colour: '#484644', label: 'FLAXPOD MATT' },
  { colour: '#4b4a49', label: 'WINDSOR GREY MATT' },
  { colour: '#5a5a58', label: 'GREY FRIARS MAT+SAT' },
  { colour: '#4f4f4e', label: 'CHARCOAL MATT+SATIN' },
  { colour: '#544e49', label: 'IRONSAND MATT+SATIN' },
  { colour: '#464544', label: 'GRAVEL MATT' },
  // { colour: '#3e3c39', label: 'BLACK MATT+SATIN' },
]